### ISSUE TITLE
Stricter Regex

### ISSUE THREAD

**Issue by awhitehatter** [bugcrowdlabs/HUNT#6]
First, and quickly, just want to say this project is awesome. Great idea! 

Second, I am getting a lot of false positive parameters from common words found in requests. 

For example: 
```
id parameter gets flagged in the word "Trident" (on the User Agent)
ip parameter gets flagged in the word "script"
field parameter gets flagged in "hiddenfield"
view parameter gets flagged in Viewstate
etc.
```

Maybe there can be a keyword exclusion list?

**Comment by swagnetow** [comment]
Hey @awhitehatter, I'm not able to reproduce what you're seeing. I actually implemented code that first checks an English dictionary to see if a parameter is a real word. If it's a real word, it's most likely a false positive; if it's not a real word, it's most likely a vuln parameter. A keyword exclusion list wouldn't work here because that type of blacklist would end up being huge.

**Comment by awhitehatter** [comment]
That makes sense, regarding the keyword list. I'll see if I can figure out why the code for the word check isn't working. Here's a screenshot:

![selection_309](https://user-images.githubusercontent.com/4513861/28889735-39409d9c-7782-11e7-8417-4415efd4b664.png)

**Comment by swagnetow** [comment]
Oh, you meant the highlighting within the request window. Sorry, I completely misunderstood what you meant. It's technically no longer an issue as it's now using Burp's actual request/response message editor instead of that text editor. Bad news is that there's no more highlighting in the newest version of HUNT because that method does not exist for the message editor that it's currently using.

I've opened up an issue with Burp:

https://support.portswigger.net/customer/portal/questions/17116042-highlighting-in-imessageeditor

**Comment by awhitehatter** [comment]
Ah, got it. Okay. I'll update to the newest version and watch for changes. Thanks.

**Comment by SJCaldwell** [comment]
I'm actually sort of confused with this as well. I recently cloned from master:

I'm told the parameter IP exists in a request:

Looking at the request, I see zip_code and zip_code_2 are both parameters. I'm assuming zip_code_2 is what gets picked up, as 2 is not a word. 

Are there plans in the future to extract the full detected name to display in the advisory panel or on the checklist? I'd love to help develop the tool! It's a great concept but I'm finding the use a little confusing. If the full name of the parameter was extracted it would also make it dead simple to highlight the full parameter name 'zip_code' instead of the generic 'id' which would make Burp's highlighting less confusing.

**Comment by swagnetow** [comment]
@SJCaldwell Yes, I just finished working on that feature of showing the fully detected parameter name in the advisory panel. Unfortunately, the plan is to implement the usage of Burp Suite's built-in request/response viewer instead of the text editor which is currently in master. That request/response viewer does NOT have access to highlighting via the API like the text editor. I've already sent in a feature request to PortSwigger for this API call.

https://support.portswigger.net/customer/portal/questions/17116042-highlighting-in-imessageeditor
